# Generated by Django 5.0.3 on 2024-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='products/static/img'),
        ),
    ]
